version: '3'
services:
  installer:
    container_name: installer
    image: mongo
    env_file: dev.env
    tty: true
    stdin_open: true
    volumes:
      - ./scripts:/usr/local/scripts
    entrypoint: ["/usr/local/scripts/setup-shard.sh"]
  shard1:
    container_name: shard1
    image: mongo
    env_file: dev.env
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/data1:/data/db
  shard2:
    container_name: shard2
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/data2:/data/db
    env_file: dev.env
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet config --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/config1:/data/db
    env_file: dev.env
  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet config --dbpath /data/db --port 27017
    volumes:
      - /mongo_cluster/config2:/data/db
    env_file: dev.env
  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb config/mongocfg1:27017 --bind_ip 0.0.0.0 --port 27017
    env_file: dev.env
  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
    command: mongos --configdb config/mongocfg1:27017 --bind_ip 0.0.0.0 --port 27017
    env_file: dev.env
